# packages in environment at D:\miniconda\envs\mnist:
#
# Name                    Version                   Build  Channel
absl-py                   0.11.0                   pypi_0    pypi
appdirs                   1.4.4                    pypi_0    pypi
argon2-cffi               20.1.0           py38he774522_1  
astunparse                1.6.3                    pypi_0    pypi
async_generator           1.10                       py_0  
atpublic                  2.1.1                    pypi_0    pypi
attrs                     20.3.0             pyhd3eb1b0_0  
backcall                  0.2.0                      py_0  
bcrypt                    3.2.0                    pypi_0    pypi
bleach                    3.2.1                      py_0  
brotlipy                  0.7.0           py38h2bbff1b_1003  
ca-certificates           2020.10.14                    0  
cachetools                4.1.1                    pypi_0    pypi
certifi                   2020.6.20          pyhd3eb1b0_3  
cffi                      1.14.3           py38hcd4344a_2  
chardet                   3.0.4           py38haa95532_1003  
colorama                  0.4.4                      py_0  
commonmark                0.9.1                    pypi_0    pypi
configobj                 5.0.6                    pypi_0    pypi
cryptography              3.2.1            py38hcd4344a_1  
cycler                    0.10.0                   pypi_0    pypi
decorator                 4.4.2                      py_0  
defusedxml                0.6.0                      py_0  
dictdiffer                0.8.1                    pypi_0    pypi
distro                    1.5.0                    pypi_0    pypi
dpath                     2.0.1                    pypi_0    pypi
dulwich                   0.20.11                  pypi_0    pypi
dvc                       1.10.1                   pypi_0    pypi
entrypoints               0.3                      py38_0  
flatten-dict              0.3.0                    pypi_0    pypi
flufl-lock                3.2                      pypi_0    pypi
ftfy                      5.8                      pypi_0    pypi
funcy                     1.15                     pypi_0    pypi
future                    0.18.2                   pypi_0    pypi
gast                      0.3.3                    pypi_0    pypi
gitdb                     4.0.5                    pypi_0    pypi
gitpython                 3.1.11                   pypi_0    pypi
google-api-core           1.23.0                   pypi_0    pypi
google-api-python-client  1.12.8                   pypi_0    pypi
google-auth               1.23.0                   pypi_0    pypi
google-auth-httplib2      0.0.4                    pypi_0    pypi
google-auth-oauthlib      0.4.2                    pypi_0    pypi
google-pasta              0.2.0                    pypi_0    pypi
googleapis-common-protos  1.52.0                   pypi_0    pypi
grandalf                  0.6                      pypi_0    pypi
grpcio                    1.33.2                   pypi_0    pypi
h5py                      2.10.0                   pypi_0    pypi
httplib2                  0.18.1                   pypi_0    pypi
idna                      2.10                       py_0  
importlib-metadata        2.0.0                      py_1  
importlib_metadata        2.0.0                         1  
invoke                    1.4.1                    pypi_0    pypi
ipykernel                 5.3.4            py38h5ca1d4c_0  
ipython                   7.19.0           py38hd4e2768_0  
ipython_genutils          0.2.0                    py38_0  
jedi                      0.17.2                   py38_0  
jinja2                    2.11.2                     py_0  
json5                     0.9.5                      py_0  
jsonpath-ng               1.5.2                    pypi_0    pypi
jsonschema                3.2.0                      py_2  
jupyter_client            6.1.7                      py_0  
jupyter_core              4.6.3                    py38_0  
jupyterlab                2.2.6                      py_0  
jupyterlab_pygments       0.1.2                      py_0  
jupyterlab_server         1.2.0                      py_0  
keras                     2.4.3                    pypi_0    pypi
keras-preprocessing       1.1.2                    pypi_0    pypi
kiwisolver                1.3.1                    pypi_0    pypi
libsodium                 1.0.18               h62dcd97_0  
m2w64-gcc-libgfortran     5.3.0                         6  
m2w64-gcc-libs            5.3.0                         7  
m2w64-gcc-libs-core       5.3.0                         7  
m2w64-gmp                 6.1.0                         2  
m2w64-libwinpthread-git   5.0.0.4634.697f757               2  
mailchecker               3.3.17                   pypi_0    pypi
markdown                  3.3.3                    pypi_0    pypi
markupsafe                1.1.1            py38he774522_0  
matplotlib                3.3.3                    pypi_0    pypi
mistune                   0.8.4           py38he774522_1000  
msys2-conda-epoch         20160418                      1  
nanotime                  0.5.2                    pypi_0    pypi
nbclient                  0.5.1                      py_0  
nbconvert                 6.0.7                    py38_0  
nbformat                  5.0.8                      py_0  
nest-asyncio              1.4.2              pyhd3eb1b0_0  
networkx                  2.4                      pypi_0    pypi
notebook                  6.1.4                    py38_0  
numpy                     1.18.5                   pypi_0    pypi
oauth2client              4.1.3                    pypi_0    pypi
oauthlib                  3.1.0                    pypi_0    pypi
openssl                   1.1.1h               he774522_0  
opt-einsum                3.3.0                    pypi_0    pypi
packaging                 20.4                       py_0  
pandoc                    2.11                 h9490d1a_0  
pandocfilters             1.4.3            py38haa95532_1  
paramiko                  2.7.2                    pypi_0    pypi
parso                     0.7.0                      py_0  
pathlib2                  2.3.5                    pypi_0    pypi
pathspec                  0.8.1                    pypi_0    pypi
phonenumbers              8.12.13                  pypi_0    pypi
pickleshare               0.7.5                 py38_1000  
pillow                    8.0.1                    pypi_0    pypi
pip                       20.2.4           py38haa95532_0  
ply                       3.11                     pypi_0    pypi
prometheus_client         0.8.0                      py_0  
prompt-toolkit            3.0.8                      py_0  
protobuf                  3.14.0                   pypi_0    pypi
pyasn1                    0.4.8                    pypi_0    pypi
pyasn1-modules            0.2.8                    pypi_0    pypi
pycparser                 2.20                       py_2  
pydot                     1.4.1                    pypi_0    pypi
pydrive2                  1.7.0                    pypi_0    pypi
pygments                  2.7.2              pyhd3eb1b0_0  
pygtrie                   2.3.2                    pypi_0    pypi
pynacl                    1.4.0                    pypi_0    pypi
pyopenssl                 19.1.0             pyhd3eb1b0_1  
pyparsing                 2.4.7                      py_0  
pyrsistent                0.17.3           py38he774522_0  
pysocks                   1.7.1            py38haa95532_0  
python                    3.8.5                h5fd99cc_1  
python-benedict           0.22.0                   pypi_0    pypi
python-dateutil           2.8.1                      py_0  
python-slugify            4.0.1                    pypi_0    pypi
pytz                      2020.4                   pypi_0    pypi
pywin32                   227              py38he774522_1  
pywinpty                  0.5.7                    py38_0  
pyyaml                    5.3.1                    pypi_0    pypi
pyzmq                     19.0.2           py38ha925a31_1  
requests                  2.24.0                     py_0  
requests-oauthlib         1.3.0                    pypi_0    pypi
rich                      9.2.0                    pypi_0    pypi
rsa                       4.6                      pypi_0    pypi
ruamel-yaml               0.16.12                  pypi_0    pypi
ruamel-yaml-clib          0.2.2                    pypi_0    pypi
scipy                     1.5.4                    pypi_0    pypi
send2trash                1.5.0                    py38_0  
setuptools                50.3.1           py38haa95532_1  
shortuuid                 1.0.1                    pypi_0    pypi
shtab                     1.3.2                    pypi_0    pypi
six                       1.15.0           py38haa95532_0  
smmap                     3.0.4                    pypi_0    pypi
sqlite                    3.33.0               h2a8f88b_0  
tabulate                  0.8.7                    pypi_0    pypi
tensorboard               2.4.0                    pypi_0    pypi
tensorboard-plugin-wit    1.7.0                    pypi_0    pypi
tensorflow                2.3.1                    pypi_0    pypi
tensorflow-estimator      2.3.0                    pypi_0    pypi
termcolor                 1.1.0                    pypi_0    pypi
terminado                 0.9.1                    py38_0  
testpath                  0.4.4                      py_0  
text-unidecode            1.3                      pypi_0    pypi
toml                      0.10.2                   pypi_0    pypi
tornado                   6.0.4            py38he774522_1  
tqdm                      4.52.0                   pypi_0    pypi
traitlets                 5.0.5                      py_0  
typing-extensions         3.7.4.3                  pypi_0    pypi
uritemplate               3.0.1                    pypi_0    pypi
urllib3                   1.25.11                    py_0  
vc                        14.1                 h0510ff6_4  
voluptuous                0.12.0                   pypi_0    pypi
vs2015_runtime            14.16.27012          hf0eaf9b_3  
wcwidth                   0.2.5                      py_0  
webencodings              0.5.1                    py38_1  
werkzeug                  1.0.1                    pypi_0    pypi
wheel                     0.35.1             pyhd3eb1b0_0  
win-unicode-console       0.5                      pypi_0    pypi
win_inet_pton             1.1.0            py38haa95532_0  
wincertstore              0.2                      py38_0  
winpty                    0.4.3                         4  
wrapt                     1.12.1                   pypi_0    pypi
xmltodict                 0.12.0                   pypi_0    pypi
zc-lockfile               2.0                      pypi_0    pypi
zeromq                    4.3.2                ha925a31_3  
zipp                      3.4.0              pyhd3eb1b0_0  
zlib                      1.2.11               h62dcd97_4  
